#!/usr/bin/env python3
"""
Build the sdist and the wheel, and refuse to let stray local files ship.

Usage:
    python tests/tools/check_dist.py [--outdir DIR]

Run by the ``package`` tox environment and by CI.  It exists because
hatchling's VCS-ignore support only honours the *root* ``.gitignore``: a file
hidden from ``git status`` by a nested ``.gitignore``, or by the developer's
global git ignore file, is invisible locally and still ends up in the
tarball.  caldav-3.2.1.tar.gz shipped ``.claude/settings.json`` and 1755
files under ``venv/`` exactly that way, and nothing in CI ever built an sdist,
so nothing noticed.

The sdist file list is checked against the working tree's tracked files: the
sdist may leave tracked files out (that is a packaging choice), but it must
never contain a file git does not track.  That is also what turns "build the
release from a clean checkout" from a rule someone has to remember into one
the build enforces.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
import tarfile
import zipfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent

## Generated by the build, so absent from git but legitimately in the dist.
GENERATED = frozenset(
    {
        "PKG-INFO",
        "caldav/_version.py",
    }
)


def _tracked_files() -> set[str]:
    out = subprocess.run(
        ["git", "-C", str(REPO_ROOT), "ls-files"],
        check=True,
        capture_output=True,
        text=True,
    )
    return set(out.stdout.split())


def _sdist_members(sdist: Path) -> set[str]:
    with tarfile.open(sdist) as tar:
        ## every member is prefixed with "<name>-<version>/"
        return {name.split("/", 1)[1] for name in tar.getnames() if "/" in name}


def _wheel_members(wheel: Path) -> set[str]:
    with zipfile.ZipFile(wheel) as zf:
        return set(zf.namelist())


def _build(outdir: Path) -> tuple[Path, Path]:
    subprocess.run(
        [sys.executable, "-m", "build", "--outdir", str(outdir), str(REPO_ROOT)],
        check=True,
    )
    (sdist,) = outdir.glob("*.tar.gz")
    (wheel,) = outdir.glob("*.whl")
    return sdist, wheel


def _twine_check(outdir: Path) -> None:
    subprocess.run(
        [sys.executable, "-m", "twine", "check", "--strict", *map(str, outdir.iterdir())],
        check=True,
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--outdir", default="dist", help="where to write the built artifacts")
    args = parser.parse_args()

    outdir = Path(args.outdir).resolve()
    outdir.mkdir(parents=True, exist_ok=True)
    for stale in outdir.iterdir():
        stale.unlink()

    sdist, wheel = _build(outdir)
    _twine_check(outdir)

    tracked = _tracked_files()
    untracked_in_sdist = sorted(_sdist_members(sdist) - tracked - GENERATED)
    if untracked_in_sdist:
        print(
            f"{len(untracked_in_sdist)} file(s) in {sdist.name} are not tracked by git:",
            file=sys.stderr,
        )
        for name in untracked_in_sdist[:50]:
            print(f"  {name}", file=sys.stderr)
        if len(untracked_in_sdist) > 50:
            print(f"  ... and {len(untracked_in_sdist) - 50} more", file=sys.stderr)
        print(
            "\nEither the release is being built from a dirty tree (build from a "
            "clean checkout - see docs/design/RELEASE-HOWTO.md), or these want an "
            "entry in [tool.hatch.build.targets.sdist] exclude in pyproject.toml.",
            file=sys.stderr,
        )
        return 1

    ## The wheel is the package and nothing else.
    stray_in_wheel = sorted(
        name
        for name in _wheel_members(wheel)
        if not name.startswith("caldav/") and ".dist-info/" not in name
    )
    if stray_in_wheel:
        print(f"unexpected files in {wheel.name}:", file=sys.stderr)
        for name in stray_in_wheel:
            print(f"  {name}", file=sys.stderr)
        return 1

    print(f"{sdist.name}: {len(_sdist_members(sdist))} files, all accounted for")
    print(f"{wheel.name}: {len(_wheel_members(wheel))} files, all accounted for")
    return 0


if __name__ == "__main__":
    sys.exit(main())
